import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/pages/Footer/Footer";
import Nav from "@/pages/CarouselandNav/Nav";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Al Mazra Enterprises LLP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {/* Navigation bar inside layout */}
        <Nav />
        <div className="pt-[100px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
